#!/usr/bin/env python
# coding: utf-8
"""
Scramble a file of newline separated sentences.

Usage:
    scramble_corpus [options] <infile>

Options:
  -f --insert=<insert>                     A source of sentences to insert.
  -x --range=<range>                       Range of sentences that are scrambled [default: 5].
  -s --swaps=<swaps>                       Number of possible sentence swaps within range [default: 1].
  -i --insertions=<insertions>             Number of possible sentence insertions within range [default: 1].
  -r --removals=<removals>                 Number of possible sentence removals within range [default: 1].
  -S --word-swaps=<word-swaps>             Number of possible word swaps within sentence [default: 1].
  -I --word-insertions=<word-insertions>   Number of possible word insertions within sentence [default: 1].
  -R --word-removals=<word-removals>       Number of possible word removals within sentence [default: 1].
"""
from docopt import docopt
from yalign.scramble import scramble

if __name__ == "__main__":
    args = docopt(__doc__)
    options = {
    "source": open(args["<infile>"]),
    "sentence_range": [5, int(args["--range"])],
    "sentence_swap_range": [0, int(args["--swaps"])],
    "sentence_insertion_range": [0, int(args["--insertions"])],
    "sentence_removal_range": [0, int(args["--removals"])],
    "word_swap_range": [0, int(args["--word-swaps"])],
    "word_insertion_range": [0, int(args["--word-insertions"])],
    "word_removal_range": [0, int(args["--word-removals"])],
    }
    if args["--insert"]:
        options["more"] = open(args["--insert"])
    for idx, sentence in enumerate(scramble(**options)):
        print idx, sentence
