#!/usr/bin/env python
# coding: utf-8
"""
Evaluate how many word alignments are found from a document pair.

Usage:
    yalign-evaluate-word-alignment <parallel-corpus> <model>
"""

from docopt import docopt
from yalign.yalignmodel import YalignModel
from yalign.evaluation import word_alignment_percentage
from yalign.input_conversion import parallel_corpus_to_documents


if __name__ == "__main__":
    args = docopt(__doc__)
    parallel_corpus = args["<parallel-corpus>"]
    A, B = parallel_corpus_to_documents(parallel_corpus)
    modelpath = args["<model>"]
    model = YalignModel()
    model.load(modelpath)

    p = word_alignment_percentage(A, B, model)
    print "Word aligment percentage: {}%".format(p)
