#!/usr/bin/env python
# coding: utf-8
"""
Generate alignment and non alignment samples from a parallel corpus.

Usage:
    yalign-make-metadata [options] <parallel-corpus> <scorer>

Options:
  -o --output=<output>             The metadata filename [default: metadata.json]
  -la --lang-a=<language>      The language of the file A [default: en]
  -lb --lang-b=<language>      The language of the file B [default: es]
  -n --number-of-tries=<number-of-tries>  Max number of tries for optimizing [default: 100]
"""

from docopt import docopt
from yalign.optimize import optimize 
from yalign.sentencepairscore import SentencePairScore
import json

if __name__ == "__main__":
    args = docopt(__doc__)
    parallel_corpus = args["<parallel-corpus>"]
    scorer = SentencePairScore()
    scorer.load(args["<scorer>"])
    N = int(args['--number-of-tries'])
    print "Optimizing with %s tries.." % N
    score, gap_penalty, threshold = optimize(parallel_corpus, scorer, N)
    metadata = dict(gap_penalty=gap_penalty,
                    threshold=threshold,
                    lang_a=args['--lang-a'],
                    lang_b=args['--lang-b'])
    json.dump(metadata, open(args['--output'], "w"))
