#!/usr/bin/env python
# coding: utf-8

"""
Evaluate docs from file of urls.

Usage:
    yalign-evaluate-docs <file_of_urls> <model_folder> <outfile>
"""

import codecs
from docopt import docopt

from yalign.yalignmodel import YalignModel
from yalign.input_conversion import html_to_document
from yalign.utils import read_from_url


def document_from_url(url):
    html = read_from_url(url)
    return html_to_document(html)


def _documents(file_of_urls):
    handler = iter(codecs.open(file_of_urls, encoding="utf-8"))
    while True:
        try:
            url_a = next(handler)
            url_b = next(handler)
            A = document_from_url(url_a.strip())
            B = document_from_url(url_b.strip())
            yield A, B
        except StopIteration:
            break


if __name__ == "__main__":
    args = docopt(__doc__)
    source = args['<file_of_urls>']
    model_folder = args['<model_folder>']
    outfile = open(args['<outfile>'], 'w')
    model = YalignModel()
    model.load(model_folder)

    for A,B in _documents(source):
        print len(A), len(B)
        alignments = model.align_indexes(A, B)
        alignments.sort()
        for idx_a, idx_b in alignments:
            outfile.write(A[idx_a].to_text()+' ||| ')
            outfile.write(B[idx_b].to_text()+'\n')
