#!/usr/bin/env python
# coding: utf-8

"""
Extract text from an html page.

Usage:
    yalign-html_to_corpus <url_or_file> <output>
"""

from docopt import docopt
from yalign.input_conversion import read_from_url
from yalign.train import html_to_corpus


def read_html(source):
    if source.startswith('http'):
        print "Reading from url:", source
        html = read_from_url(source)
    else:
        print "Reading from file:", source
        html = open(source).read()
    return html

if __name__ == "__main__":
    args = docopt(__doc__)
    source = args['<url_or_file>']
    html = read_html(source)
    output = open(args['<output>'], 'w')
    for sentence in html_to_corpus(html):
        output.write(sentence.encode('utf-8') + '\n')
