#!/usr/bin/env python
# coding: utf-8
"""
Evaluate the porcentage of words that are in the translation dictionary.

Usage:
    yalign-evaluate-translations-alignment <parallel-corpus> <model>
"""

from docopt import docopt
from yalign.yalignmodel import YalignModel
from yalign.evaluation import word_translations_percentage
from yalign.input_conversion import parallel_corpus_to_documents


if __name__ == "__main__":
    args = docopt(__doc__)
    parallel_corpus = args["<parallel-corpus>"]
    A, B = parallel_corpus_to_documents(parallel_corpus)
    modelpath = args["<model>"]
    model = YalignModel()
    model.load(modelpath)
    p = word_translations_percentage(A, B, model)
    print "Words in the dictionary: {}%".format(p)
