#!/usr/bin/env python
# coding: utf-8

"""
Extract text from an html page.

Usage:
    yalign-make-model [options] <tmx_file> <output_folder>

Options:
  -s --source-lang=<language>      The Source language [default: en]
  -t --target-lang=<language>      The target language [default: es]
  -n --number-of-tries=<number-of-tries>  Max number of tries for optimizing [default: 10]
"""

import os
import shutil
from docopt import docopt

if __name__ == "__main__":
    args = docopt(__doc__)
    folder = args['<output_folder>']
    tmx_file = os.path.abspath(args['<tmx_file>'])
    if os.path.isdir(folder):
        path = os.path.dirname(os.path.abspath(__file__))
        makefile = os.path.join(path, 'Makefile')
        shutil.copy(makefile, folder)
        os.chdir(folder)
        makefile_args = (tmx_file, args['--source-lang'], args['--target-lang'], args['--number-of-tries'])
        os.system("make create-model TMX_FILE=%s SOURCE_LANG=%s TARGET_LANG=%s MAX_TRIES=%s" % makefile_args)
