#!/usr/bin/env python
# coding: utf-8

"""
Extract text from an html page.

Usage:
    text_to_corpus <input> <output>
"""

from docopt import docopt
from yalign.train import text_to_corpus

if __name__ == "__main__":
    args = docopt(__doc__)
    source = open(args['<input>'])
    output = open(args['<output>'], 'w')
    text = source.read()
    for line in text_to_corpus(text):
        output.write(line + '\n')
