#!/usr/bin/env python
# coding: utf-8

"""
Trains the TU Classifier to score the alignment of two sentences

Usage:
    yalign-tuscore [options] <dataset> <word_scores> <outfile>

Dataset must be a csv file with examples of aligned and not aligned sentences
Word scores must be the output of the wordscore script

Options:
  -e --eval        Evaluates a training using 10-fold
  -h --help        Show this screen.
"""

import sys
from docopt import docopt
from yalign import tuscore


if __name__ == "__main__":
    args = docopt(__doc__)

    dataset_filepath = args["<dataset>"]
    out_filepath = args["<outfile>"]
    word_scores = args["<word_scores>"]

    if args["--eval"]:
        from simpleai.machine_learning import kfold
        training_data = tuscore.parse_training_data(dataset_filepath)
        problem = tuscore.SentenceProblem(word_scores)
        score = kfold(training_data, problem, tuscore.SVMClassifier)
        message = "Classifier precision {:.3f}% (10-fold crossvalidation)"
        print >> sys.stderr, message.format(score * 100)
        exit(0)

    print >> sys.stderr, "Starting training"
    tuscore.train_and_save_classifier(dataset_filepath, word_scores, out_filepath)
    print >> sys.stderr, "Training done"
