#!/usr/bin/env python
# coding: utf-8

"""
Generate alignment and non alignment samples from a parallel corpus.

Usage:
    yalign-generate-samples <parallel-corpus> <outfile>
"""

from docopt import docopt
from yalign.train import samples
import csv

if __name__ == "__main__":
    args = docopt(__doc__)
    parallel_corpus = open(args["<parallel-corpus>"])
    outfile = csv.writer(open(args["<outfile>"], "w"), quoting=csv.QUOTE_NONNUMERIC)
    outfile.writerow(["aligned", "src N", "src idx", "src", "tgt N", "tgt idx", "tgt"])
    for x in samples(parallel_corpus):
        outfile.writerow(x)
